print('hello world!')
print('what is your name?')
myName = input()
print('it is good to meet you,' + myName)
print('The lengh of your name is:')
print(len(myName))
print('What is your age?')
myAge = input()
print('You will be ' + str(int(myAge) + 1 ) + ' in a year.')